--DEPARTMENTS
INSERT INTO DEPARTMENTS (NAME_DEP) VALUES ('Management');
INSERT INTO DEPARTMENTS (NAME_DEP) VALUES ('Sales');
INSERT INTO DEPARTMENTS (NAME_DEP) VALUES ('Marketing');
INSERT INTO DEPARTMENTS (NAME_DEP) VALUES ('TestDepartment');

--EMPLOYEES
INSERT INTO EMPLOYEES (FIO, DATE_OF_BIRTH, SALARY, NAME_DEP) VALUES ('York Peter Steven', '1990-10-01', 200, 'Sales');
INSERT INTO EMPLOYEES (FIO, DATE_OF_BIRTH, SALARY, NAME_DEP) VALUES ('Warren Pen Oliver', '1967-12-21', 243, 'Sales');
INSERT INTO EMPLOYEES (FIO, DATE_OF_BIRTH, SALARY, NAME_DEP) VALUES ('Shelton Mark Paul', '1983-01-11', 500, 'Management');
INSERT INTO EMPLOYEES (FIO, DATE_OF_BIRTH, SALARY, NAME_DEP) VALUES ('McDaniel Winfred Darren', '1996-12-15', 350, 'Marketing');
INSERT INTO EMPLOYEES (FIO, DATE_OF_BIRTH, SALARY, NAME_DEP) VALUES ('Warren Brian Oliver', '1991-12-16', 560, 'Marketing');




